### ISSUE TITLE
Run local without installing globally

### ISSUE THREAD

**Issue by royts** [JFrogDev/bower-art-resolver#13]
Hi,

Is there a way to run the resolver locally without installing globally?
Usually I'm just running the binary files directly, and it works perfectly with gulp, bower, etc.

In _bower-art-resolver_ case I don't see a binary file, and trying the following fails:

``` json
{
    "registry": "http://some.artifactory.repo",
    "resolvers": [
        "../node_modules/bower-art-resolver/lib/index"
    ]
}
```

All works good when installing _bower-art-resolver_ globally.

Any idea?

thanks.

**Comment by eyalbe4** [comment]
Hi @royts ,
Installing the resolver locally is not supported, but you can configure the resolver for specific projects only, by placing a private .bowerrc file it in the current working directory as mentioned in the [Bower Configuration](http://bower.io/docs/config/) page.

**Comment by royts** [comment]
Thanks @eyalbe4 .
I forgot to update here - I found some answer in bower github issues list (can't find a link now), that simply pointed that bower will look for the resolver globally and then locally.

It is working great now.

Thanks!
