### ISSUE TITLE
Version mismatch in NPM

### ISSUE THREAD

**Issue by dougmoscrop** [JFrogDev/bower-art-resolver#2]
See: https://www.npmjs.com/package/bower-art-resolver

This does not appear to be published to NPM yet, which is totally cool but there is another thing already published there that does not work with Bower 1.5.2 but has a newer version (1.0.5-) than this (1.0.0). Maybe it was written to work with your `bower-art` and the final Bower API does not match.

Either way it would be cool to publish this (ideally with my search fix :shameless plug:) and maybe deprecate the other one.

**Comment by liorhson** [comment]
Hey,
We plan to official publish Artifactory resolver (bower-art-resolver) in the next two weeks with version **2.0.0**.
The old resolver that you saw in npm; indeed was written to work with `bower-art`, which will not be needed starting from bower version 1.5.0.

**Comment by dougmoscrop** [comment]
Yeah, it was more for people who have been sort of watching the issue, if they just `npm install bower-art-resolver` they get a version that looks "legit" (i.e 1.0.0 has a sort of connotation to it) but it fails with weird error messages.
