### ISSUE TITLE
Update to request 2.74.0

### ISSUE THREAD

**Issue by prycec** [JFrogDev/bower-art-resolver#22]
To address https://nodesecurity.io/advisories/130

**Comment by eyalbe4** [comment]
[This](https://github.com/JFrogDev/bower-art-resolver/pull/25/files) pull request upgrades _request_ to this version.

**Comment by Trainmaster** [comment]
@eyalbe4 This can be closed due to https://github.com/JFrogDev/bower-art-resolver/pull/25

**Comment by eyalbe4** [comment]
Thanks @Trainmaster. Closing.
