### ISSUE TITLE
API url validation

### ISSUE THREAD

**Issue by ghost** [JFrogDev/bower-art-resolver#4]
Hey guys,

I'm just giving a try to this and found you require the string ["artifactory" in the repository url](https://github.com/JFrogDev/bower-art-resolver/blob/master/lib/utils.js#L68-L73). 

Is that really necesary?

I.e.: set a host name for the bower repo like bower.mycompanyrepo.com to point artifactory's API through rewrite rules...

**Comment by eyalbe4** [comment]
@nicolas-vellon, we certainly wouldn't want to require having the string "artifactory" as part of the URL.
If this is indeed the case, this is something we'd like to fix.
We will check this. Thank you for reporting this.

**Comment by eyalbe4** [comment]
This issue will be fixed as part of the next release.

**Comment by ghost** [comment]
+1

**Comment by eyalbe4** [comment]
@nicolas-vellon, version 2.0.2 with this fix has been published.

**Comment by eyalbe4** [comment]
@mithun, @rschick,
We committed the change.
Before publishing this change, can you please try it out by installing it as follows?
_npm install -g https://github.com/JFrogDev/bower-art-resolver.git_

With this change, you can configure the Artifactory URL in two ways:

``` json
{   
    "registry": "http://localhost:8080/artifactory/api/bower/bower-virtual",
    "resolvers": [
      "bower-art-resolver"
    ]
}
```

or if you wish to use different URLs for resolution from Artifactory and for registering packages:

``` json
{
    "registry": {
      "register": "https://bower.herokuapp.com",
      "search": [
        "http://localhost:8080/artifactory/api/bower/bower-virtual",
        "https://bower.herokuapp.com"
      ]
    },
    "resolvers": [
      "bower-art-resolver"
    ]
}
```

**Comment by mithun** [comment]
i ran a quick test. A `bower info` and `bower install` works fine

**Comment by rschick** [comment]
Works great, thanks @eyalbe4

**Comment by eyalbe4** [comment]
Thank you @mithun and @rschick !
New version is published.
